public enum PickupType
{
	MONEY_SMALL = 0,
	MONEY_LARGE = 1,
	ITEM_CROWN = 2,
	WEAPON_PICK = 3,
	WEAPON_SWORD = 4,
	WEAPON_UNARMED = 5,
	WEAPON_SHIELD = 6,
	WEAPON_CLUB = 7,
	WEAPON_BOW = 8,
	SKILL_MAGNET = 9,
	SKILL_FLIGHT = 10,
	SKILL_SHOTGUN = 11,
	SKILL_TELEPORT = 12,
	SKILL_SHOT = 13,
	MAX = 14
}
